[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["alembic upgrade head || echo 'Migration skipped'"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

